#!/bin/bash
git add .
git commit -m "script to Write a script that deletes all the regular files (not the directories) with a .js extension that are present in the current directory and all its subfolders."
git push
